<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add New Rider' => 'Ku dar Add Rider',
    'Add New Status' => 'Ku dar Xaaladda Cusub',
    'Address' => 'Address',
    'Address  ID' => 'Aqoonsiga cinwaanka',
    'Are you sure you want to delete this item?' => '',
    'CSV' => '',
    'Cities' => '',
    'City  Models' => '',
    'Comma Separated Values' => '',
    'Countries' => '',
    'Country  Models' => '',
    'Create City' => '',
    'Create City  Model' => '',
    'Create Country' => '',
    'Create Location' => '',
    'Create Rider' => '',
    'Create Size' => '',
    'Date' => '',
    'Delete' => '',
    'Description' => '',
    'Designated Kitchen' => '',
    'Excel 2007+' => '',
    'Excel 95 +' => '',
    'Hot Deal' => '',
    'Image' => '',
    'Kitchen Management' => '',
    'Kitchen Queue' => '',
    'Location' => '',
    'Location  ID' => '',
    'Locations' => '',
    'Max Item Per Customer' => '',
    'Menu Category' => '',
    'Menu Item' => '',
    'Menu Item Name' => '',
    'Microsoft Excel 2007+ (xlsx)' => '',
    'Microsoft Excel 95+ (xls)' => '',
    'Order Status Management' => '',
    'Pizza Out' => '',
    'Reset' => '',
    'Reset Grid' => '',
    'Rider  Models' => '',
    'Rider Active' => '',
    'Rider Name' => '',
    'Rider Orders' => '',
    'Riders' => '',
    'Save' => '',
    'Search' => '',
    'Select Account Type' => '',
    'Select Kitchen' => '',
    'Sizes' => '',
    'Status li' => '',
    'The CSV export file will be generated for download.' => '',
    'The EXCEL 2007+ (xlsx) export file will be generated for download.' => '',
    'The EXCEL 95+ (xls) export file will be generated for download.' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update City: {nameAttribute}' => '',
    'Update Country' => '',
    'Update Location' => '',
    'Update Password' => '',
    'Update Rider' => '',
    'Update Size: {nameAttribute}' => '',
    'Update Status: {nameAttribute}' => '',
    'User  ID' => '',
    'Vegetarian' => '',
    'View Status: {nameAttribute}' => '',
    'Sizes  Models' => '@@@@',
];
