<?php
/**
 * Created by PhpStorm.
 * User: RONIN
 * Date: 7/16/2017
 * Time: 8:47 PM
 */

namespace app\api\modules\v1\controllers;

use app\api\modules\v1\models\CART_MODEL;
use app\api\modules\v1\models\MENU_ITEM_MODEL;
use yii\rest\ActiveController;
use yii\web\ForbiddenHttpException;


class CustomeraddressController extends ActiveController
{
    /**
     * @var object
     */
    public $modelClass = 'app\api\modules\v1\models\CUSTOMER_ADDRESS_MODEL';

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        //unset($actions['update']);
        return $actions;
    }

}