<?php
/**
 * Created by PhpStorm.
 * User: RONIN
 * Date: 7/16/2017
 * Time: 8:47 PM
 */

namespace app\api\modules\v1\controllers;

use app\api\modules\v1\models\CART_MODEL;
use app\api\modules\v1\models\MENU_ITEM_MODEL;
use app\api\modules\v1\models\TRACKING_MODEL;
use yii\db\Exception;
use yii\rest\ActiveController;
use yii\web\ForbiddenHttpException;


class TimelineController extends ActiveController
{
    /**
     * @var object
     */
    public $modelClass = 'app\api\modules\v1\models\TRACKING_MODEL';

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index']); //disable these
        return $actions;
    }

    /**
     * Checks the privilege of the current user.
     *
     * This method should be overridden to check whether the current user has the privilege
     * to run the specified action against the specified data model.
     * If the user does not have access, a [[ForbiddenHttpException]] should be thrown.
     *
     * @param string $action the ID of the action to be executed
     * @param \yii\base\Model $model the model to be accessed. If `null`, it means no specific model is being accessed.
     * @param array $params additional parameters
     * @throws ForbiddenHttpException if the user does not have access
     * @throws \yii\web\ForbiddenHttpException
     */
    public function checkAccessOld($action, $model = null, $params = [])
    {
        throw new \yii\web\ForbiddenHttpException(sprintf('You can only %s articles that you\'ve created.', $action));

    }

    /**
     * @throws Exception
     */
    public function actionIndex()
    {
        throw new Exception('Not allowed', 404);
    }

    /**
     * @param $order_id
     * @return TRACKING_MODEL[]|array|\yii\db\ActiveRecord[]
     */
    public function actionActiveOrders($order_id)
    {
        $orderTimeline = TRACKING_MODEL::find()
            ->where(['ORDER_ID' => $order_id])
            ->andWhere(['USER_VISIBLE' => 1])
            ->orderBy(['TRACKING_DATE' => SORT_ASC])
            ->all();

        return $orderTimeline;
    }

}